version: '3.3'
services: 
    java-server:
        image: 'openjdk:12'
        container_name: java-server-container
        volumes: 
            - ./app:/root/project
        command: bash -c "cd /root/project && javac br/ifc/server/PaymentServer.java && java br/ifc/server/PaymentServer"
        ports:
            - '3333:3333'
